# Repeated K-Fold

In [14]:
import numpy as np
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
print(X)
random_state = 12883823
rkf = RepeatedKFold(n_splits=2, n_repeats=1, random_state=random_state)
for train, test in rkf.split(X):
    print("%s %s" % (train, test))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[2 3] [0 1]
[0 1] [2 3]


In [13]:
import numpy as np
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
print(X)
random_state = 12883823
rkf = RepeatedKFold(n_splits=2, n_repeats=2, random_state=random_state)
for train, test in rkf.split(X):
    print("%s %s" % (train, test))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[2 3] [0 1]
[0 1] [2 3]
[0 2] [1 3]
[1 3] [0 2]


In [17]:
import numpy as np
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
print(X)
random_state = 12883823
rkf = RepeatedKFold(n_splits=2, n_repeats=3, random_state=random_state)
for train, test in rkf.split(X):
    print("%s %s" % (train, test))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[2 3] [0 1]
[0 1] [2 3]
[0 2] [1 3]
[1 3] [0 2]
[0 3] [1 2]
[1 2] [0 3]


In [26]:
import numpy as np
from sklearn.model_selection import KFold

X = ["a", "b", "c", "d"]
kf = KFold(n_splits=2)
for train, test in kf.split(X):
    print("%s %s" % (train, test))

[2 3] [0 1]
[0 1] [2 3]


In [38]:
X = np.array([[0., 0.], [1., 1.], [-1., -1.], [2., 2.]])
y = np.array([1, 2, 3, 4])
print(X)
print(y)
X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]
print("train:",X_train, y_train)
print("test: ",X_test, y_test)

[[ 0.  0.]
 [ 1.  1.]
 [-1. -1.]
 [ 2.  2.]]
[1 2 3 4]
train: [[0. 0.]
 [1. 1.]] [1 2]
test:  [[-1. -1.]
 [ 2.  2.]] [3 4]


In [53]:
import numpy as np
from sklearn.model_selection import KFold

X = np.array([[0., 0.], [1., 1.], [-1., -1.], [2., 2.],[3., 5.],[4., 6.]])
y = np.array([1, 2, 3, 4,5,6])
print("X and y:")
print(X)
print(y)
kf = RepeatedKFold(n_splits=3,n_repeats=2,random_state=2652124)
i=1
for train_index, test_index  in kf.split(X):
    
    print("loop: ", i)
    print("train, test split:")
    print("%s %s" % (train, test))
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]
    print("X train, y train:",X_train, y_train)
    print("X test, y test: ",X_test, y_test)
    i+=1

X and y:
[[ 0.  0.]
 [ 1.  1.]
 [-1. -1.]
 [ 2.  2.]
 [ 3.  5.]
 [ 4.  6.]]
[1 2 3 4 5 6]
loop:  1
train, test split:
[2 3 4 5] [0 1]
X train, y train: [[ 0.  0.]
 [-1. -1.]
 [ 3.  5.]
 [ 4.  6.]] [1 3 5 6]
X test, y test:  [[1. 1.]
 [2. 2.]] [2 4]
loop:  2
train, test split:
[2 3 4 5] [0 1]
X train, y train: [[1. 1.]
 [2. 2.]
 [3. 5.]
 [4. 6.]] [2 4 5 6]
X test, y test:  [[ 0.  0.]
 [-1. -1.]] [1 3]
loop:  3
train, test split:
[2 3 4 5] [0 1]
X train, y train: [[ 0.  0.]
 [ 1.  1.]
 [-1. -1.]
 [ 2.  2.]] [1 2 3 4]
X test, y test:  [[3. 5.]
 [4. 6.]] [5 6]
loop:  4
train, test split:
[2 3 4 5] [0 1]
X train, y train: [[0. 0.]
 [1. 1.]
 [2. 2.]
 [4. 6.]] [1 2 4 6]
X test, y test:  [[-1. -1.]
 [ 3.  5.]] [3 5]
loop:  5
train, test split:
[2 3 4 5] [0 1]
X train, y train: [[-1. -1.]
 [ 2.  2.]
 [ 3.  5.]
 [ 4.  6.]] [3 4 5 6]
X test, y test:  [[0. 0.]
 [1. 1.]] [1 2]
loop:  6
train, test split:
[2 3 4 5] [0 1]
X train, y train: [[ 0.  0.]
 [ 1.  1.]
 [-1. -1.]
 [ 3.  5.]] [1 2 3 5]
X test

In [57]:
kf = KFold(n_splits=3,random_state=2652124)
for train_index, test_index  in kf.split(X):
    print(train_index,test_index)

[2 3 4 5] [0 1]
[0 1 4 5] [2 3]
[0 1 2 3] [4 5]


C:\Users\DNN\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(


In [55]:
kf = RepeatedKFold(n_splits=3,n_repeats=2,random_state=2652124)
for train_index, test_index  in kf.split(X):
    print(train_index,test_index)

[0 2 4 5] [1 3]
[1 3 4 5] [0 2]
[0 1 2 3] [4 5]
[0 1 3 5] [2 4]
[2 3 4 5] [0 1]
[0 1 2 4] [3 5]


In [19]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

X, y = datasets.load_iris(return_X_y=True)
X.shape, y.shape


((150, 4), (150,))

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=0)

X_train.shape, y_train.shape

X_test.shape, y_test.shape

clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

clf.score(X_test, y_test)

0.9666666666666667